# 사이트 공통 설정
# 배포 도메인 확정 후 BASE_URL 을 실제 도메인으로 변경하세요.
BASE_URL = "https://www.songpa-ganda.example.com"

BRAND = "간다GO"
PHONE = "0508-202-4719"
PHONE_DISPLAY = "0508-202-4719"

# 상단 메뉴 — 하위 메뉴에는 키워드를 반복하지 않고 지역명·역명만 표시한다.
# 하위 항목의 href 가 None 이면 클릭되지 않는 그룹 라벨(노선 구분)로 렌더링된다.
NAV = [
    ("홈", "/", []),
    ("송파 출장마사지", "/massage/", [
        ("출장마사지 안내", "/massage/#service"),
        ("홈타이 안내", "/massage/#hometai"),
        ("전지역 방문 안내", "/massage/#coverage"),
        ("지하철역 인근 안내", "/massage/#stations"),
        ("예약 가능 시간", "/massage/#hours"),
        ("코스 선택 안내", "/massage/#course"),
        ("이용 전 확인사항", "/massage/#check"),
        ("위생·안전 안내", "/massage/#safety"),
        ("자주 묻는 질문", "/massage/#faq"),
    ]),
    ("지역별 안내", "/songpa/", [
        ("송파구 전체", "/songpa/"),
        ("풍납동", "/songpa/pungnap-dong/"),
        ("거여동", "/songpa/geoyeo-dong/"),
        ("마천동", "/songpa/macheon-dong/"),
        ("방이동", "/songpa/bangi-dong/"),
        ("오금동", "/songpa/ogeum-dong/"),
        ("송파동", "/songpa/songpa-dong/"),
        ("석촌동", "/songpa/seokchon-dong/"),
        ("삼전동", "/songpa/samjeon-dong/"),
        ("가락동", "/songpa/garak-dong/"),
        ("문정동", "/songpa/munjeong-dong/"),
        ("장지동", "/songpa/jangji-dong/"),
        ("위례동", "/songpa/wirye-dong/"),
        ("잠실동", "/songpa/jamsil-dong/"),
        ("신천동", "/songpa/sincheon-dong/"),
    ]),
    # 환승역(잠실·종합운동장·가락시장·오금·석촌·올림픽공원)은 노선마다 노출하되
    # URL 은 역당 하나만 사용한다.
    ("지하철역별 안내", "/songpa/stations/", [
        ("역 전체", "/songpa/stations/"),
        ("2호선 송파권", None),
        ("잠실나루역", "/songpa/stations/jamsillaru-station/"),
        ("잠실역", "/songpa/stations/jamsil-station/"),
        ("잠실새내역", "/songpa/stations/jamsilsaenae-station/"),
        ("종합운동장역", "/songpa/stations/sports-complex-station/"),
        ("3호선 송파권", None),
        ("가락시장역", "/songpa/stations/garak-market-station/"),
        ("경찰병원역", "/songpa/stations/national-police-hospital-station/"),
        ("오금역", "/songpa/stations/ogeum-station/"),
        ("5호선 송파권", None),
        ("방이역", "/songpa/stations/bangi-station/"),
        ("오금역", "/songpa/stations/ogeum-station/"),
        ("개롱역", "/songpa/stations/gaerong-station/"),
        ("거여역", "/songpa/stations/geoyeo-station/"),
        ("마천역", "/songpa/stations/macheon-station/"),
        ("올림픽공원역", "/songpa/stations/olympic-park-station/"),
        ("8호선 송파권", None),
        ("몽촌토성역", "/songpa/stations/mongchontoseong-station/"),
        ("잠실역", "/songpa/stations/jamsil-station/"),
        ("석촌역", "/songpa/stations/seokchon-station/"),
        ("송파역", "/songpa/stations/songpa-station/"),
        ("가락시장역", "/songpa/stations/garak-market-station/"),
        ("문정역", "/songpa/stations/munjeong-station/"),
        ("장지역", "/songpa/stations/jangji-station/"),
        ("복정역", "/songpa/stations/bokjeong-station/"),
        ("9호선 송파권", None),
        ("종합운동장역", "/songpa/stations/sports-complex-station/"),
        ("삼전역", "/songpa/stations/samjeon-station/"),
        ("석촌고분역", "/songpa/stations/seokchon-gobun-station/"),
        ("석촌역", "/songpa/stations/seokchon-station/"),
        ("송파나루역", "/songpa/stations/songpanaru-station/"),
        ("한성백제역", "/songpa/stations/hanseong-baekje-station/"),
        ("올림픽공원역", "/songpa/stations/olympic-park-station/"),
    ]),
    ("테마별 안내", "/themes/", [
        ("전체 테마", "/themes/"),
        ("스웨디시", "/themes/swedish/"),
        ("로미로미", "/themes/lomilomi/"),
        ("타이마사지", "/themes/thai/"),
        ("중국마사지", "/themes/chinese/"),
        ("아로마테라피", "/themes/aroma/"),
        ("홈케어", "/themes/homecare/"),
        ("호텔식마사지", "/themes/hotel-style/"),
        ("발마사지", "/themes/foot/"),
        ("스포츠·경락", "/themes/sports/"),
        ("스킨케어", "/themes/skincare/"),
        ("왁싱", "/themes/waxing/"),
        ("커플 관리", "/themes/couple/"),
        ("24시간", "/themes/24hours/"),
        ("수면 가능", "/themes/overnight/"),
    ]),
    ("코스안내", "/courses/", [
        ("전체 코스", "/courses/"),
        ("피로 회복 관리", "/courses/#recovery"),
        ("아로마 관리", "/courses/#aroma"),
        ("스포츠 관리", "/courses/#sports"),
        ("홈타이 코스", "/courses/#hometai"),
        ("커플·가족 방문 관리", "/courses/#couple"),
        ("기업·단체 방문 관리", "/courses/#group"),
        ("가격 안내", "/courses/#price"),
        ("코스 선택 가이드", "/courses/#guide"),
    ]),
    ("예약안내", "/reservation/", [
        ("예약 방법", "/reservation/#how"),
        ("예약 가능 시간", "/reservation/#hours"),
        ("방문 가능 장소", "/reservation/#place"),
        ("결제 안내", "/reservation/#payment"),
        ("변경·취소 안내", "/reservation/#change"),
        ("예약 전 체크사항", "/reservation/#check"),
    ]),
    ("이용가이드", "/guide/", [
        ("처음 이용하시는 분", "/guide/#first"),
        ("방문 전 준비사항", "/guide/#prepare"),
        ("위생 및 안전 기준", "/guide/#hygiene"),
        ("관리 후 주의사항", "/guide/#after"),
        ("금지행위 안내", "/guide/#prohibited"),
        ("이용 FAQ", "/guide/#faq"),
    ]),
    ("매거진", "/magazine/", [
        ("전체 글", "/magazine/"),
        ("출장 vs 샵 비교", "/magazine/visiting-vs-shop/"),
        ("코스 시간 고르기", "/magazine/60-90-120-course/"),
        ("좌식 근무와 허리", "/magazine/desk-worker-back/"),
        ("마사지 전후 스트레칭", "/magazine/stretching-with-massage/"),
        ("환절기 컨디션 관리", "/magazine/seasonal-fatigue/"),
        ("출산 후 회복 관리", "/magazine/postpartum-care/"),
    ]),
    ("후기", "/reviews/", [
        ("전체 후기", "/reviews/"),
        ("지역별 후기", "/reviews/#area"),
        ("역세권 후기", "/reviews/#station"),
        ("후기 작성 안내", "/reviews/#write"),
    ]),
    ("고객센터", "/support/", [
        ("공지사항", "/support/#notice"),
        ("자주 묻는 질문", "/support/#faq"),
        ("1:1 문의", "/support/#contact"),
        ("제휴·기업 문의", "/support/#biz"),
        ("개인정보처리방침", "/support/privacy/"),
        ("이용약관", "/support/terms/"),
    ]),
]
